/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

package com.abiquo.abiserver.business.hibernate.pojohb.virtualappliance;

// Generated 16-oct-2008 16:52:14 by Hibernate Tools 3.2.1.GA

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.pojo.virtualappliance.Node;
import com.abiquo.abiserver.pojo.virtualappliance.NodeType;

/**
 * Nodes generated by hbm2java
 */
public class NodeHB<T extends Node< ? >> implements java.io.Serializable, IPojoHB<Node< ? >>
{

    private static final long serialVersionUID = 8658661577766502632L;

    protected int idNode;

    protected String name;

    protected int idVirtualApp;

    protected NodeTypeEnum type;

    protected int posX;

    protected int posY;

    protected int modified;

    public NodeHB()
    {

    }

    public NodeHB(NodeHB< ? > node)
    {
        idNode = node.idNode;
        name = node.name;
        idVirtualApp = node.idVirtualApp;
        type = node.type;

        posX = node.posX;
        posY = node.posY;

    }

    public NodeTypeEnum getType()
    {
        return type;
    }

    public void setType(NodeTypeEnum type)
    {
        this.type = type;
    }

    public int getIdNode()
    {
        return idNode;
    }

    public void setIdNode(int idNode)
    {
        this.idNode = idNode;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public int getIdVirtualApp()
    {
        return idVirtualApp;
    }

    public void setIdVirtualApp(int idVirtualApp)
    {
        this.idVirtualApp = idVirtualApp;
    }

    public int getPosX()
    {
        return posX;
    }

    public void setPosX(int posX)
    {
        this.posX = posX;
    }

    public int getPosY()
    {
        return posY;
    }

    public void setPosY(int posY)
    {
        this.posY = posY;
    }

    public int getModified()
    {
        return modified;
    }

    public void setModified(int modified)
    {
        this.modified = modified;
    }

    public Node< ? > toPojo()
    {
        Node< ? > node = new Node<NodeHB< ? >>();
        node.setId(idNode);
        node.setIdVirtualAppliance(idVirtualApp);
        node.setName(name);
        node.setNodeType(new NodeType(type));
        node.setModified(modified);

        node.setPosX(posX);
        node.setPosY(posY);

        return node;
    }
}
