/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.20 at 10:17:04 AM CEST 
//


package com.abiquo.virtualfactory.vlan;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.abiquo.virtualfactory.vlan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VLANDelete_QNAME = new QName("http://abiquo.com/virtualfactory/vlan.xsd", "VLANDelete");
    private final static QName _VLANCreate_QNAME = new QName("http://abiquo.com/virtualfactory/vlan.xsd", "VLANCreate");
    private final static QName _VLANPut_QNAME = new QName("http://abiquo.com/virtualfactory/vlan.xsd", "VLANPut");
    private final static QName _VLANGet_QNAME = new QName("http://abiquo.com/virtualfactory/vlan.xsd", "VLANGet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.abiquo.virtualfactory.vlan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VLANCreate }
     * 
     */
    public VLANCreate createVLANCreate() {
        return new VLANCreate();
    }

    /**
     * Create an instance of {@link VLANPut }
     * 
     */
    public VLANPut createVLANPut() {
        return new VLANPut();
    }

    /**
     * Create an instance of {@link VLANDelete }
     * 
     */
    public VLANDelete createVLANDelete() {
        return new VLANDelete();
    }

    /**
     * Create an instance of {@link VLANGet }
     * 
     */
    public VLANGet createVLANGet() {
        return new VLANGet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VLANDelete }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://abiquo.com/virtualfactory/vlan.xsd", name = "VLANDelete")
    public JAXBElement<VLANDelete> createVLANDelete(VLANDelete value) {
        return new JAXBElement<VLANDelete>(_VLANDelete_QNAME, VLANDelete.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VLANCreate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://abiquo.com/virtualfactory/vlan.xsd", name = "VLANCreate")
    public JAXBElement<VLANCreate> createVLANCreate(VLANCreate value) {
        return new JAXBElement<VLANCreate>(_VLANCreate_QNAME, VLANCreate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VLANPut }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://abiquo.com/virtualfactory/vlan.xsd", name = "VLANPut")
    public JAXBElement<VLANPut> createVLANPut(VLANPut value) {
        return new JAXBElement<VLANPut>(_VLANPut_QNAME, VLANPut.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VLANGet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://abiquo.com/virtualfactory/vlan.xsd", name = "VLANGet")
    public JAXBElement<VLANGet> createVLANGet(VLANGet value) {
        return new JAXBElement<VLANGet>(_VLANGet_QNAME, VLANGet.class, null, value);
    }

}
