/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

package com.abiquo.api.pools;

import org.apache.commons.pool.BasePoolableObjectFactory;

import com.abiquo.server.core.infrastructure.RemoteService;

/**
 * base class for factories to create remote service clients that will be placed in the pool.
 * 
 * @author Ignasi Barrera
 */
public abstract class PoolableRemoteServiceClientFactory extends BasePoolableObjectFactory
{
    /** The target remote service where clients in this pool will connect. */
    protected RemoteService remoteService;

    /**
     * Creates the factory to generate remote service clients for the given remote service.
     * 
     * @param remoteService The remote service where clients generated by this factory will connect.
     */
    public PoolableRemoteServiceClientFactory(final RemoteService remoteService)
    {
        super();
        this.remoteService = remoteService;
    }
}
