package com.abiquo.api.pools;

import org.apache.commons.pool.BasePoolableObjectFactory;

import com.abiquo.server.core.infrastructure.RemoteService;

/**
 * base class for factories to create remote service clients that will be placed in the pool.
 * 
 * @author Ignasi Barrera
 */
public abstract class PoolableRemoteServiceClientFactory extends BasePoolableObjectFactory
{
    /** The target remote service where clients in this pool will connect. */
    protected RemoteService remoteService;

    /**
     * Creates the factory to generate remote service clients for the given remote service.
     * 
     * @param remoteService The remote service where clients generated by this factory will connect.
     */
    public PoolableRemoteServiceClientFactory(final RemoteService remoteService)
    {
        super();
        this.remoteService = remoteService;
    }
}
