/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

package com.abiquo.api.exceptions.mapper;

import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Response;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;

import com.abiquo.api.handlers.InputParamConstraintHandler;

/**
 * Handles validation errors generated by validation at resource level.
 * 
 * @author Ignasi Barrera
 * @author Jaume Devesa
 * @see InputParamConstraintHandler
 */
@Provider
public class ConstraintViolationExceptionMapper implements ExceptionMapper<WebApplicationException>
{
    /**
     * The exception that will be handled has already been parsed by the
     * {@link InputParamConstraintHandler} class, and the response it contains is already well
     * formed and ready to be returned.
     */
    @Override
    public Response toResponse(final WebApplicationException exception)
    {
        return exception.getResponse();
    }
}
