/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 01:07:44 PM CET 
//


package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_resourceallocationsettingdata;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.dmtf.schemas.ovf.envelope._1.RASDType;
import org.dmtf.schemas.wbem.wscim._1.common.CimBoolean;
import org.dmtf.schemas.wbem.wscim._1.common.CimString;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedInt;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedLong;
import org.w3c.dom.Element;


/**
 * <p>Java class for CIM_ResourceAllocationSettingData_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIM_ResourceAllocationSettingData_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Address" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AddressOnParent" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AllocationUnits" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AutomaticAllocation" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}AutomaticDeallocation" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Caption" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ChangeableType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ConfigurationName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Connection" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ConsumerVisibility" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Description" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ElementName"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Generation" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}HostResource" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}InstanceID"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Limit" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}MappingBehavior" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}OtherResourceType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Parent" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}PoolID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Reservation" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ResourceSubType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}ResourceType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}VirtualQuantity" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData}Weight" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIM_ResourceAllocationSettingData_Type", propOrder = {
    "address",
    "addressOnParent",
    "allocationUnits",
    "automaticAllocation",
    "automaticDeallocation",
    "caption",
    "changeableType",
    "configurationName",
    "connection",
    "consumerVisibility",
    "description",
    "elementName",
    "generation",
    "hostResource",
    "instanceID",
    "limit",
    "mappingBehavior",
    "otherResourceType",
    "parent",
    "poolID",
    "reservation",
    "resourceSubType",
    "resourceType",
    "virtualQuantity",
    "weight",
    "any"
})
@XmlSeeAlso({
    RASDType.class
})
public class CIMResourceAllocationSettingDataType {

    @XmlElement(name = "Address", nillable = true, required=false)
    protected CimString address;
    @XmlElement(name = "AddressOnParent", nillable = true, required=false)
    protected CimString addressOnParent;
    @XmlElement(name = "AllocationUnits", nillable = true, required=false)
    protected CimString allocationUnits;
    @XmlElement(name = "AutomaticAllocation", nillable = true, required=false)
    protected CimBoolean automaticAllocation;
    @XmlElement(name = "AutomaticDeallocation", nillable = true, required=false)
    protected CimBoolean automaticDeallocation;
    @XmlElement(name = "Caption", nillable = true, required=false)
    protected Caption caption;
    @XmlElement(name = "ChangeableType", nillable = true, required=false)
    protected ChangeableType changeableType;
    @XmlElement(name = "ConfigurationName", nillable = true, required=false)
    protected CimString configurationName;
    @XmlElement(name = "Connection", nillable = true, required=false)
    protected List<CimString> connection;
    @XmlElement(name = "ConsumerVisibility", nillable = true, required=false)
    protected ConsumerVisibility consumerVisibility;
    @XmlElement(name = "Description", nillable = true, required=false)
    protected CimString description;
    @XmlElement(name = "ElementName", required = true)
    protected CimString elementName;
    @XmlElement(name = "Generation", nillable = true, required=false)
    protected CimUnsignedLong generation;
    @XmlElement(name = "HostResource", nillable = true, required=false)
    protected List<CimString> hostResource;
    @XmlElement(name = "InstanceID", required = true)
    protected CimString instanceID;
    @XmlElement(name = "Limit", nillable = true, required=false)
    protected CimUnsignedLong limit;
    @XmlElement(name = "MappingBehavior", nillable = true, required=false)
    protected MappingBehavior mappingBehavior;
    @XmlElement(name = "OtherResourceType", nillable = true, required=false)
    protected CimString otherResourceType;
    @XmlElement(name = "Parent", nillable = true, required=false)
    protected CimString parent;
    @XmlElement(name = "PoolID", nillable = true, required=false)
    protected CimString poolID;
    @XmlElement(name = "Reservation", nillable = true, required=false)
    protected CimUnsignedLong reservation;
    @XmlElement(name = "ResourceSubType", nillable = true, required=false)
    protected CimString resourceSubType;
    @XmlElement(name = "ResourceType", nillable = true)
    protected ResourceType resourceType;
    @XmlElement(name = "VirtualQuantity", nillable = true, required=false)
    protected CimUnsignedLong virtualQuantity;
    @XmlElement(name = "Weight", nillable = true, required=false)
    protected CimUnsignedInt weight;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setAddress(CimString value) {
        this.address = value;
    }

    /**
     * Gets the value of the addressOnParent property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getAddressOnParent() {
        return addressOnParent;
    }

    /**
     * Sets the value of the addressOnParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setAddressOnParent(CimString value) {
        this.addressOnParent = value;
    }

    /**
     * Gets the value of the allocationUnits property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getAllocationUnits() {
        return allocationUnits;
    }

    /**
     * Sets the value of the allocationUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setAllocationUnits(CimString value) {
        this.allocationUnits = value;
    }

    /**
     * Gets the value of the automaticAllocation property.
     * 
     * @return
     *     possible object is
     *     {@link CimBoolean }
     *     
     */
    public CimBoolean getAutomaticAllocation() {
        return automaticAllocation;
    }

    /**
     * Sets the value of the automaticAllocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimBoolean }
     *     
     */
    public void setAutomaticAllocation(CimBoolean value) {
        this.automaticAllocation = value;
    }

    /**
     * Gets the value of the automaticDeallocation property.
     * 
     * @return
     *     possible object is
     *     {@link CimBoolean }
     *     
     */
    public CimBoolean getAutomaticDeallocation() {
        return automaticDeallocation;
    }

    /**
     * Sets the value of the automaticDeallocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimBoolean }
     *     
     */
    public void setAutomaticDeallocation(CimBoolean value) {
        this.automaticDeallocation = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link Caption }
     *     
     */
    public Caption getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Caption }
     *     
     */
    public void setCaption(Caption value) {
        this.caption = value;
    }

    /**
     * Gets the value of the changeableType property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeableType }
     *     
     */
    public ChangeableType getChangeableType() {
        return changeableType;
    }

    /**
     * Sets the value of the changeableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeableType }
     *     
     */
    public void setChangeableType(ChangeableType value) {
        this.changeableType = value;
    }

    /**
     * Gets the value of the configurationName property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getConfigurationName() {
        return configurationName;
    }

    /**
     * Sets the value of the configurationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setConfigurationName(CimString value) {
        this.configurationName = value;
    }

    /**
     * Gets the value of the connection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CimString }
     * 
     * 
     */
    public List<CimString> getConnection() {
        if (connection == null) {
            connection = new ArrayList<CimString>();
        }
        return this.connection;
    }

    /**
     * Gets the value of the consumerVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerVisibility }
     *     
     */
    public ConsumerVisibility getConsumerVisibility() {
        return consumerVisibility;
    }

    /**
     * Sets the value of the consumerVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerVisibility }
     *     
     */
    public void setConsumerVisibility(ConsumerVisibility value) {
        this.consumerVisibility = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setDescription(CimString value) {
        this.description = value;
    }

    /**
     * Gets the value of the elementName property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getElementName() {
        return elementName;
    }

    /**
     * Sets the value of the elementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setElementName(CimString value) {
        this.elementName = value;
    }

    /**
     * Gets the value of the generation property.
     * 
     * @return
     *     possible object is
     *     {@link CimUnsignedLong }
     *     
     */
    public CimUnsignedLong getGeneration() {
        return generation;
    }

    /**
     * Sets the value of the generation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimUnsignedLong }
     *     
     */
    public void setGeneration(CimUnsignedLong value) {
        this.generation = value;
    }

    /**
     * Gets the value of the hostResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CimString }
     * 
     * 
     */
    public List<CimString> getHostResource() {
        if (hostResource == null) {
            hostResource = new ArrayList<CimString>();
        }
        return this.hostResource;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setInstanceID(CimString value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link CimUnsignedLong }
     *     
     */
    public CimUnsignedLong getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimUnsignedLong }
     *     
     */
    public void setLimit(CimUnsignedLong value) {
        this.limit = value;
    }

    /**
     * Gets the value of the mappingBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link MappingBehavior }
     *     
     */
    public MappingBehavior getMappingBehavior() {
        return mappingBehavior;
    }

    /**
     * Sets the value of the mappingBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingBehavior }
     *     
     */
    public void setMappingBehavior(MappingBehavior value) {
        this.mappingBehavior = value;
    }

    /**
     * Gets the value of the otherResourceType property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getOtherResourceType() {
        return otherResourceType;
    }

    /**
     * Sets the value of the otherResourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setOtherResourceType(CimString value) {
        this.otherResourceType = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setParent(CimString value) {
        this.parent = value;
    }

    /**
     * Gets the value of the poolID property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getPoolID() {
        return poolID;
    }

    /**
     * Sets the value of the poolID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setPoolID(CimString value) {
        this.poolID = value;
    }

    /**
     * Gets the value of the reservation property.
     * 
     * @return
     *     possible object is
     *     {@link CimUnsignedLong }
     *     
     */
    public CimUnsignedLong getReservation() {
        return reservation;
    }

    /**
     * Sets the value of the reservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimUnsignedLong }
     *     
     */
    public void setReservation(CimUnsignedLong value) {
        this.reservation = value;
    }

    /**
     * Gets the value of the resourceSubType property.
     * 
     * @return
     *     possible object is
     *     {@link CimString }
     *     
     */
    public CimString getResourceSubType() {
        return resourceSubType;
    }

    /**
     * Sets the value of the resourceSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimString }
     *     
     */
    public void setResourceSubType(CimString value) {
        this.resourceSubType = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceType }
     *     
     */
    public ResourceType getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceType }
     *     
     */
    public void setResourceType(ResourceType value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the virtualQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link CimUnsignedLong }
     *     
     */
    public CimUnsignedLong getVirtualQuantity() {
        return virtualQuantity;
    }

    /**
     * Sets the value of the virtualQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimUnsignedLong }
     *     
     */
    public void setVirtualQuantity(CimUnsignedLong value) {
        this.virtualQuantity = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link CimUnsignedInt }
     *     
     */
    public CimUnsignedInt getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link CimUnsignedInt }
     *     
     */
    public void setWeight(CimUnsignedInt value) {
        this.weight = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
