/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 12:44:58 PM CEST 
//


package com.abiquo.server.core.infrastructure.nodecollector;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HypervisorEnumTypeDto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HypervisorEnumTypeDto">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="kvm"/>
 *     &lt;enumeration value="esxi"/>
 *     &lt;enumeration value="vbox"/>
 *     &lt;enumeration value="xen"/>
 *     &lt;enumeration value="hyperv"/>
 *     &lt;enumeration value="xenserver"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HypervisorEnumTypeDto")
@XmlEnum
public enum HypervisorEnumTypeDto {

    @XmlEnumValue("kvm")
    KVM("kvm"),
    @XmlEnumValue("esxi")
    ESXI("esxi"),
    @XmlEnumValue("vbox")
    VBOX("vbox"),
    @XmlEnumValue("xen")
    XEN("xen"),
    @XmlEnumValue("hyperv")
    HYPERV("hyperv"),
    @XmlEnumValue("xenserver")
    XENSERVER("xenserver");
    private final String value;

    HypervisorEnumTypeDto(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HypervisorEnumTypeDto fromValue(String v) {
        for (HypervisorEnumTypeDto c: HypervisorEnumTypeDto.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
