/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.23 at 01:07:44 PM CET 
//


package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_virtualsystemsettingdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.dmtf.schemas.wbem.wscim._1.common.CimDateTime;
import org.dmtf.schemas.wbem.wscim._1.common.CimString;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedLong;
import org.dmtf.schemas.wbem.wscim._1.common.CimUnsignedShort;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_virtualsystemsettingdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigurationName_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ConfigurationName");
    private final static QName _RecoveryFile_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "RecoveryFile");
    private final static QName _Caption_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "Caption");
    private final static QName _CIMVirtualSystemSettingData_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "CIM_VirtualSystemSettingData");
    private final static QName _ConfigurationFile_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ConfigurationFile");
    private final static QName _SuspendDataRoot_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "SuspendDataRoot");
    private final static QName _VirtualSystemIdentifier_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "VirtualSystemIdentifier");
    private final static QName _AutomaticShutdownAction_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticShutdownAction");
    private final static QName _Description_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "Description");
    private final static QName _SwapFileDataRoot_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "SwapFileDataRoot");
    private final static QName _AutomaticStartupActionSequenceNumber_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticStartupActionSequenceNumber");
    private final static QName _InstanceID_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "InstanceID");
    private final static QName _Generation_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "Generation");
    private final static QName _AutomaticStartupActionDelay_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticStartupActionDelay");
    private final static QName _VirtualSystemType_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "VirtualSystemType");
    private final static QName _AutomaticRecoveryAction_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticRecoveryAction");
    private final static QName _AutomaticStartupAction_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "AutomaticStartupAction");
    private final static QName _ConfigurationID_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ConfigurationID");
    private final static QName _ElementName_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ElementName");
    private final static QName _ChangeableType_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ChangeableType");
    private final static QName _CreationTime_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "CreationTime");
    private final static QName _Notes_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "Notes");
    private final static QName _SnapshotDataRoot_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "SnapshotDataRoot");
    private final static QName _ConfigurationDataRoot_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "ConfigurationDataRoot");
    private final static QName _LogDataRoot_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", "LogDataRoot");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_virtualsystemsettingdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CIMVirtualSystemSettingDataType }
     * 
     */
    public CIMVirtualSystemSettingDataType createCIMVirtualSystemSettingDataType() {
        return new CIMVirtualSystemSettingDataType();
    }

    /**
     * Create an instance of {@link AutomaticStartupAction }
     * 
     */
    public AutomaticStartupAction createAutomaticStartupAction() {
        return new AutomaticStartupAction();
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link AutomaticRecoveryAction }
     * 
     */
    public AutomaticRecoveryAction createAutomaticRecoveryAction() {
        return new AutomaticRecoveryAction();
    }

    /**
     * Create an instance of {@link AutomaticShutdownAction }
     * 
     */
    public AutomaticShutdownAction createAutomaticShutdownAction() {
        return new AutomaticShutdownAction();
    }

    /**
     * Create an instance of {@link ChangeableType }
     * 
     */
    public ChangeableType createChangeableType() {
        return new ChangeableType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ConfigurationName")
    public JAXBElement<CimString> createConfigurationName(CimString value) {
        return new JAXBElement<CimString>(_ConfigurationName_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "RecoveryFile")
    public JAXBElement<CimString> createRecoveryFile(CimString value) {
        return new JAXBElement<CimString>(_RecoveryFile_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Caption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Caption")
    public JAXBElement<Caption> createCaption(Caption value) {
        return new JAXBElement<Caption>(_Caption_QNAME, Caption.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMVirtualSystemSettingDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "CIM_VirtualSystemSettingData")
    public JAXBElement<CIMVirtualSystemSettingDataType> createCIMVirtualSystemSettingData(CIMVirtualSystemSettingDataType value) {
        return new JAXBElement<CIMVirtualSystemSettingDataType>(_CIMVirtualSystemSettingData_QNAME, CIMVirtualSystemSettingDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ConfigurationFile")
    public JAXBElement<CimString> createConfigurationFile(CimString value) {
        return new JAXBElement<CimString>(_ConfigurationFile_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "SuspendDataRoot")
    public JAXBElement<CimString> createSuspendDataRoot(CimString value) {
        return new JAXBElement<CimString>(_SuspendDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "VirtualSystemIdentifier")
    public JAXBElement<CimString> createVirtualSystemIdentifier(CimString value) {
        return new JAXBElement<CimString>(_VirtualSystemIdentifier_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutomaticShutdownAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticShutdownAction")
    public JAXBElement<AutomaticShutdownAction> createAutomaticShutdownAction(AutomaticShutdownAction value) {
        return new JAXBElement<AutomaticShutdownAction>(_AutomaticShutdownAction_QNAME, AutomaticShutdownAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Description")
    public JAXBElement<CimString> createDescription(CimString value) {
        return new JAXBElement<CimString>(_Description_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "SwapFileDataRoot")
    public JAXBElement<CimString> createSwapFileDataRoot(CimString value) {
        return new JAXBElement<CimString>(_SwapFileDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticStartupActionSequenceNumber")
    public JAXBElement<CimUnsignedShort> createAutomaticStartupActionSequenceNumber(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_AutomaticStartupActionSequenceNumber_QNAME, CimUnsignedShort.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "InstanceID")
    public JAXBElement<CimString> createInstanceID(CimString value) {
        return new JAXBElement<CimString>(_InstanceID_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedLong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Generation")
    public JAXBElement<CimUnsignedLong> createGeneration(CimUnsignedLong value) {
        return new JAXBElement<CimUnsignedLong>(_Generation_QNAME, CimUnsignedLong.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticStartupActionDelay")
    public JAXBElement<CimDateTime> createAutomaticStartupActionDelay(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_AutomaticStartupActionDelay_QNAME, CimDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "VirtualSystemType")
    public JAXBElement<CimString> createVirtualSystemType(CimString value) {
        return new JAXBElement<CimString>(_VirtualSystemType_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutomaticRecoveryAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticRecoveryAction")
    public JAXBElement<AutomaticRecoveryAction> createAutomaticRecoveryAction(AutomaticRecoveryAction value) {
        return new JAXBElement<AutomaticRecoveryAction>(_AutomaticRecoveryAction_QNAME, AutomaticRecoveryAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutomaticStartupAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "AutomaticStartupAction")
    public JAXBElement<AutomaticStartupAction> createAutomaticStartupAction(AutomaticStartupAction value) {
        return new JAXBElement<AutomaticStartupAction>(_AutomaticStartupAction_QNAME, AutomaticStartupAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ConfigurationID")
    public JAXBElement<CimString> createConfigurationID(CimString value) {
        return new JAXBElement<CimString>(_ConfigurationID_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ElementName")
    public JAXBElement<CimString> createElementName(CimString value) {
        return new JAXBElement<CimString>(_ElementName_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ChangeableType")
    public JAXBElement<ChangeableType> createChangeableType(ChangeableType value) {
        return new JAXBElement<ChangeableType>(_ChangeableType_QNAME, ChangeableType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "CreationTime")
    public JAXBElement<CimDateTime> createCreationTime(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_CreationTime_QNAME, CimDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "Notes")
    public JAXBElement<CimString> createNotes(CimString value) {
        return new JAXBElement<CimString>(_Notes_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "SnapshotDataRoot")
    public JAXBElement<CimString> createSnapshotDataRoot(CimString value) {
        return new JAXBElement<CimString>(_SnapshotDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "ConfigurationDataRoot")
    public JAXBElement<CimString> createConfigurationDataRoot(CimString value) {
        return new JAXBElement<CimString>(_ConfigurationDataRoot_QNAME, CimString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", name = "LogDataRoot")
    public JAXBElement<CimString> createLogDataRoot(CimString value) {
        return new JAXBElement<CimString>(_LogDataRoot_QNAME, CimString.class, null, value);
    }

}
