/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

package com.abiquo.abiserver.pojo.authorization;

import com.abiquo.abiserver.business.hibernate.pojohb.authorization.AuthResourceHB;
import com.abiquo.abiserver.pojo.IPojo;
import com.abiquo.abiserver.pojo.user.Role;

// Generated 17-oct-2008 18:40:48 by Hibernate Tools 3.2.1.GA

/**
 * AuthClientresource generated by hbm2java
 */
public class Resource implements IPojo<AuthResourceHB>
{

    private int id;

    private String name;

    private String description;

    private Group group;

    private Role role;

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public Group getGroup()
    {
        return group;
    }

    public void setGroup(Group group)
    {
        this.group = group;
    }

    public Role getRole()
    {
        return role;
    }

    public void setRole(Role role)
    {
        this.role = role;
    }

    public AuthResourceHB toPojoHB()
    {

        AuthResourceHB authResourceHB = new AuthResourceHB();

        authResourceHB.setId(id);
        authResourceHB.setName(name);
        authResourceHB.setDescription(description);
        authResourceHB.setRoleHB(role.toPojoHB());
        authResourceHB.setAuthGroupHB(group.toPojoHB());

        return authResourceHB;
    }

}
