/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

package com.abiquo.abiserver.business.hibernate.pojohb.authorization;

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.business.hibernate.pojohb.user.RoleHB;
import com.abiquo.abiserver.pojo.authorization.Resource;

// Generated 17-oct-2008 18:40:48 by Hibernate Tools 3.2.1.GA

/**
 * AuthServerresource generated by hbm2java
 */
public class AuthResourceHB implements java.io.Serializable, IPojoHB<Resource>
{

    private static final long serialVersionUID = -7686797625448816736L;

    private Integer id;

    private String name;

    private String description;

    private AuthGroupHB authGroupHB;

    private RoleHB roleHB;

    public AuthResourceHB()
    {
    }

    public Integer getId()
    {
        return id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public AuthGroupHB getAuthGroupHB()
    {
        return authGroupHB;
    }

    public void setAuthGroupHB(AuthGroupHB authGroupHB)
    {
        this.authGroupHB = authGroupHB;
    }

    public RoleHB getRoleHB()
    {
        return roleHB;
    }

    public void setRoleHB(RoleHB roleHB)
    {
        this.roleHB = roleHB;
    }

    public Resource toPojo()
    {
        Resource resource = new Resource();

        resource.setId(id);
        resource.setName(name);
        resource.setDescription(description);
        resource.setGroup(authGroupHB.toPojo());
        resource.setRole(roleHB.toPojo());

        return resource;
    }

}
