/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.01 at 11:03:17 AM CET 
//

package com.abicloud.model.test.infrastructure;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.abiquo.model.enumerator.HypervisorType;

/**
 * <p>
 * Java class for Machine complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Machine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HypervisorType" type="{http://www.abicloud.com/model/test/infrastructure}HypervisorType" />
 *       &lt;attribute name="RAM" type="{http://www.w3.org/2001/XMLSchema}int" default="4" />
 *       &lt;attribute name="CPU" type="{http://www.w3.org/2001/XMLSchema}int" default="2" />
 *       &lt;attribute name="HD" type="{http://www.w3.org/2001/XMLSchema}int" default="80" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Machine")
public class Machine
{

    @XmlAttribute(name = "Name")
    protected String name;

    @XmlAttribute(name = "IP")
    protected String ip;

    @XmlAttribute(name = "HypervisorType")
    protected HypervisorType hypervisorType;

    @XmlAttribute(name = "RAM")
    protected Integer ram;

    @XmlAttribute(name = "CPU")
    protected Integer cpu;

    @XmlAttribute(name = "HD")
    protected Integer hd;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setName(String value)
    {
        this.name = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return possible object is {@link String }
     */
    public String getIP()
    {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setIP(String value)
    {
        this.ip = value;
    }

    /**
     * Gets the value of the hypervisorType property.
     * 
     * @return possible object is {@link HypervisorType }
     */
    public HypervisorType getHypervisorType()
    {
        return hypervisorType;
    }

    /**
     * Sets the value of the hypervisorType property.
     * 
     * @param value allowed object is {@link HypervisorType }
     */
    public void setHypervisorType(HypervisorType value)
    {
        this.hypervisorType = value;
    }

    /**
     * Gets the value of the ram property.
     * 
     * @return possible object is {@link Integer }
     */
    public int getRAM()
    {
        if (ram == null)
        {
            return 4;
        }
        else
        {
            return ram;
        }
    }

    /**
     * Sets the value of the ram property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setRAM(Integer value)
    {
        this.ram = value;
    }

    /**
     * Gets the value of the cpu property.
     * 
     * @return possible object is {@link Integer }
     */
    public int getCPU()
    {
        if (cpu == null)
        {
            return 2;
        }
        else
        {
            return cpu;
        }
    }

    /**
     * Sets the value of the cpu property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setCPU(Integer value)
    {
        this.cpu = value;
    }

    /**
     * Gets the value of the hd property.
     * 
     * @return possible object is {@link Integer }
     */
    public int getHD()
    {
        if (hd == null)
        {
            return 80;
        }
        else
        {
            return hd;
        }
    }

    /**
     * Sets the value of the hd property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setHD(Integer value)
    {
        this.hd = value;
    }

}
