/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

package com.abiquo.abiserver.business.hibernate.pojohb.virtualimage;

// Generated 16-oct-2008 16:52:14 by Hibernate Tools 3.2.1.GA

import com.abiquo.abiserver.business.hibernate.pojohb.IPojoHB;
import com.abiquo.abiserver.pojo.virtualimage.Category;

/**
 * Category generated by hbm2java
 */
public class CategoryHB implements java.io.Serializable, IPojoHB<Category>
{

    private static final long serialVersionUID = -8898009103132690113L;

    private Integer idCategory;

    private String name;

    private int isErasable;

    private int isDefault;

    public Integer getIdCategory()
    {
        return idCategory;
    }

    public void setIdCategory(Integer idCategory)
    {
        this.idCategory = idCategory;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public int getIsErasable()
    {
        return isErasable;
    }

    public void setIsErasable(int isErasable)
    {
        this.isErasable = isErasable;
    }

    public int getIsDefault()
    {
        return isDefault;
    }

    public void setIsDefault(int isDefault)
    {
        this.isDefault = isDefault;
    }

    public Category toPojo()
    {
        Category category = new Category();
        category.setId(idCategory);
        category.setName(name);
        category.setIsErasable(isErasable == 1 ? true : false);
        category.setIsDefault(isDefault == 1 ? true : false);

        return category;
    }

}
